### ISSUE TITLE
as_flowFrame for creating a FCS brings an error

### ISSUE THREAD

**Issue by jgarces02** [ParkerICI/premessa#32]
Hi premessa-team,

I've got a problem trying to generate a FCS file, because most of events has an unidentifiable error once generated and opened in a flow software: 

![image](https://user-images.githubusercontent.com/27858969/73669801-63bcf780-46a8-11ea-903a-c5dfaa4e9958.png)

This is the code I used, maybe I'm miss-considering something...
```

file_q <- read.FCS("tmp.fcs")
write.FCS(as_flowFrame(as.matrix(exprs(file_q)), source.frame = file_q), "p1_asFlowFrame.fcs")
```
... but creating a `flowFrame` manually these errors (it seems) disappear.
```
file_q <- read.FCS("tmp.fcs")
write.FCS(flowFrame(exprs(file_q), file_q@parameters, description = file_q@description), "p1_flowFrame.fcs")
```
Could you explain me, if you please, if I'm doing something wrong, please? Thanks for your help.

**Comment by pfgherardini** [comment]
Can you please share the file on Box/Dropbox so that i can take a look?

**Comment by jgarces02** [comment]
I think the problem could be in the `source.flowFrame` option... maybe it's not considering correctly all parameters. Here you have the [FCS with errors](https://drive.google.com/file/d/1Jsq1_NjIyNzcCcj4uV_uzHjQncjE7VQ2/view?usp=sharing) (it's not the one which I used to open the issue, but the problem is the same). Thanks for your help.

**Comment by SamGG** [comment]
Hi,
FlowIO does not report any none compliance to the FCS 3 standard. So I am confident in the fact that the file format is correct.
![image](https://user-images.githubusercontent.com/3333348/78647947-90b1a480-78bb-11ea-9024-ef1ff8ae1cc5.png)

My hypothesis is that what could get wrong is the range of parameters. Both Premessa and flowCore are doing their job correctly as we already discussed a few months ago.
Let's investigate your corrupted file. The 1st paramaters contains values that range up to 20 included, but the range encoded in the FCS is 19. So there are 3998 values of 20 that could be truncated down to 19 depending of the software that will read that FCS file. There are also 254 lines or cells that contains NaN values, which sounds quite weird to me (a total of 5588 NA values).
You are using as_flowFrame() with a source.frame flowFrame. In that case, keywords, including range, are copied from this defined flowFrame, and not recomputed from the data.
When writing using "flowFrame manually" we also end up with a range of 19 because the flowFrame function is taking range definition from file_q@parameters. So, this content is also wrong from a range point of view.
So I don't think there is something wrong with the as_flowFrame function itself. There is rather an error in the reference source.frame. Same when using flowCore functions directly. This wrong range calculation reminds me of a bug in Cytofkit.
Whatever, the range problem does not seem to be the errors reported by the flow software (Infinicyt?), because there are 52341 values greater then their range, concerning 44196 lines or cells.
So, it would be good to know exactly what those errors are. Any log somewhere?
PS: I am not sure I am going to continue working on that because it took at least 1 hour of work.

**Comment by jgarces02** [comment]
I don't understand exactly what's happening creating this FCS... the fact is that I created the FCS manually, I mean, building a new parameters and description objects and adding them to `flowCore::write.FCS` and it works correctly (so, in the meanwhile, it's not needed to waste your time anymore). Thanks a lot for your help.

**Comment by SamGG** [comment]
Thanks for the feedback.
The main point is not the error with Premessa, but the fact that your clustering channel (or sample id channel) will be incorrectly interpreted/read back if truncate_max argument of read.FCS function is set to TRUE (as it is by default) or if the flow software is doing some similar truncation.
Best.

**Comment by jgarces02** [comment]
And you'd know any possible solution/idea for avoiding this truncation, please?

**Comment by pfgherardini** [comment]
As @SamGG correctly pointed out i believe the problem was that the clustering_som column had NA's in it. I just released a new version (0.2.6) that should fix the problem. Please install and test. I am closing the issue but feel free to reopen if the issue persists.

**Comment by SamGG** [comment]
@pfgherardini Removing NA is a good point I even didn't think about.
@jgarces02 to avoid truncation set truncate_max_range = FALSE when calling read.FCS. It's TRUE by default. I would advise you to read every argument of the read and write functions. I always set transformation to FALSE also.
Best.

**Comment by jgarces02** [comment]
Thanks a lot to both of you! I'll test the new version!

**Comment by jgarces02** [comment]
It seems it works correctly (new but also old version... 😓). Thanks anyway!

**Comment by jgarces02** [comment]
It worked perfectly, thanks a lot!

**Comment by SamGG** [comment]
@jgarces02 thanks for the feedback
@pfgherardini thanks for the update
