### ISSUE TITLE
I can't install premessa using R version 4.0.0

### ISSUE THREAD

**Issue by MLTWhite** [ParkerICI/premessa#36]
Hi! I have version R 4.0.0 and I tried to download the install_github("ParkerICI/premessa") but it doesn't work. I tried to download the vctrs package as well. Can you help me, please? Thanks
![Screen Shot 2020-05-13 at 11 56 29 AM](https://user-images.githubusercontent.com/61512322/81847474-e4de2300-9510-11ea-9ec2-4d3dec5d3fef.png)
![Screen Shot 2020-05-13 at 11 56 42 AM](https://user-images.githubusercontent.com/61512322/81847484-e7407d00-9510-11ea-8802-14bb20247561.png)

**Comment by SamGG** [comment]
Hi,
I'm not the developer. I installed premessa without any problem last week. I tested the panel editor. I am working on Windows 10 x64. I didn't not encounter the error you show.
It's very surprising that the installation skipped flowCore. If you are going to work on FCS files, install it first. See documentation on BioConductor.
Whatever, the final error is linked to the missing tool xcrun. This is what you have to solve first if you wish to install packages from source. I would recommend to install from binary (even if it seems not to be the latest version, this will probably avoid the need of xcrun) and to avoid updating packages during package installation.
So, the error is not due to premessa. If you don't understand what you say, find a R practitionner in your neighborhood.
Best.

**Comment by MLTWhite** [comment]
Thank you for your response. I am working on a Mac desktop (macOS High Sierra Version 10.13.6). It didn't allow me to install Bioconductor directly.  I needed to install BiocManager first. Also, I do have the flowCore installed but for some reason keeps giving me this error. I will check this on Windows and see. I will follow your advice as well and see what happens. Thank you. I appreciate your help!

**Comment by MLTWhite** [comment]
I solved my problem. Thank you! :)

**Comment by SamGG** [comment]
Nice. Report your solution if you feel this can help others.
Best.

**Comment by MLTWhite** [comment]
Sure! I followed the instructions from ReadMe but when I wanted to install Bioconductor didn't work so I followed the steps from this link:
https://bioconductor.org/install/

After this, when I tried to used install_github("ParkerICI/premessa"), it didn't work either so I downloaded the ".tar.gz" file from this link:
https://github.com/ParkerICI/premessa/releases/tag/v0.2.6

Then, I install it in the following way:
![Screen Shot 2020-05-13 at 9 16 25 PM](https://user-images.githubusercontent.com/61512322/81888922-90ae5f80-955f-11ea-8591-f5273901dd3d.png)
and I used the ".tar.gz" file from above. 

I hope it helps someone.
Thanks!
